name: Sync with S3 on push
on:
  push:
    branches:
      - main
      
jobs:
  s3_sync_static_website:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: configure AWS secrets
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET }}
          aws-region: us-east-1
          
      - name: sync files
        run: |
          aws s3 sync <LOCAL_PATH> s3://<BUCKET_NAME> --acl public-read
        env:
          LOCAL_PATH: ~/Match-Out
          BUCKET_NAME: flippedoutgame
      - name: Cleanup
        run: rm -rf <LOCAL_PATH>
