name: Sync with S3 on push
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      
jobs:
  s3_sync_static_website:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: configure AWS secrets
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET }}
          aws-region: us-east-1
          
      - name: sync files
        run: |
          aws s3 sync . s3://flippedoutgame  \
          --exclude ".git/*" \
          --exclude ".github/*" \
          --exclude "README.md" \
          --exclude "example_scores.html" \
          --exclude ".vscode/*" \
          --include "*.html" \
          --include "css/*" \
          --include "js/*" \
          --include "images/*" \
          --include "sounds/*" \
          --acl public-read 

      - name: Complete
        run: echo "Sync complete"
